version: "3.9"

services:
  educantrol-app:
    container_name: educantrol-app-container-compose
    image: educantrol-app
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - educantrol-db
    environment:
      - DB_HOST=educantrol-db-container-compose
  educantrol-db:
    container_name: educantrol-db-container-compose
    image: educantrol-db
    build:
      context: .
      dockerfile: Dockerfile.db
    ports:
      - "3306:3306"
